### ISSUE TITLE
Need to write a function to delete the setup git config step 

### ISSUE THREAD

**Issue by lazyplatypus** [bitprj/cabin#7]
We need to write a function to delete this part of the workflow to allow the student to see the checkmark for success!

<img width="809" alt="Screen Shot 2021-03-05 at 4 34 04 PM" src="https://user-images.githubusercontent.com/10321085/110188624-3e317e80-7dd1-11eb-9508-9c14be8940da.png">

**Comment by emsesc** [comment]
main.yml file is now deleted on start of a course
